export const TRANSLATIONS = {
    en: {
        nav: {
            home: 'Home',
            analyze: 'Analysis',
            intel: 'Intelligence',
            admin: 'Admin Map',
            map: 'India Map',
            tools: 'Tools',
            faq: 'FAQ',
            feedback: 'Feedback',
            badges: 'Badges',
            signIn: 'Sign In',
            signOut: 'Sign Out',
            signedInAs: 'Signed in as',
            sendFeedback: 'Send Feedback'
        },
        common: {
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            yes: 'YES',
            no: 'NO',
            helpful: 'Was this helpful?',
            noResults: 'No results found',
            clearFilters: 'Clear All Filters',
            contactSupport: 'Contact Support',
            stillQuestions: 'Still have questions?',
            supportDesc: 'Our team is here to help you with any water-related concerns.',
            searchPlaceholder: 'Search questions...',
            knowledgeBase: 'Knowledge Base',
            questions: 'Questions',
            faqDesc: 'Find answers to common questions about water quality, safety, and how to use our monitoring tools.',
            tryAdjust: 'Try adjusting your search or category filter.'
        },
        hero: {
            label: 'Government Initiative',
            titleStart: 'Empowering Every Citizen’s Voice in',
            titleEnd: 'Water Governance',
            desc: 'A bilingual voice assistant that helps citizens report water pollution, track complaints, and access governance services instantly.',
            btnPrimary: 'Start AI Analysis',
            btnSecondary: 'Help & FAQ'
        },
        dashboard: {
            liveMonitor: 'Live Basin Monitoring',
            liveMonitorSub: 'Real-time sensor data & community reports',
            systemOp: 'System Operational',
            aiAnalysis: 'Situation Analysis',
            viewReport: 'View Full Report',
            chartTitle: 'Water Quality Trend',
            chartSub: '7-Day Composite Index',
            keyParams: 'Key Parameters',
            recentReports: 'Recent Citizen Reports',
            submitReport: 'Submit Report',
            uploadPhoto: 'Upload photos for diagnostic analysis'
        },
        map: {
            title: 'Water Quality Map',
            subtitle: 'Regional water risks and issues',
            all: 'All',
            critical: 'Critical',
            high: 'High',
            medium: 'Medium',
            low: 'Low',
            keyIssues: 'Key Issues',
            getAdvice: 'Get Advice'
        },
        analysis: {
            title: "Visual Water Intelligence",
            subtitle: "Upload a photo of your water sample. Our advanced AI will analyze clarity, color, and sediment levels to provide an instant safety score.",
            aiPowered: "AI-Powered Diagnostics",
            howItWorks: "How it works",
            viewHistory: "View History",
            certified: "Certified Analysis",
            accuracy: "92% Accuracy Rate",
            uploadSample: "1. Upload Sample",
            clickToUpload: "Click to upload photo",
            dragDrop: "or drag and drop here",
            location: "Location (Optional)",
            locationPlaceholder: "e.g., Mau Bridge, Azamgarh",
            startAnalysis: "Start AI Analysis",
            analyzing: "Analyzing...",
            diagnosticResults: "2. Diagnostic Results",
            scanning: "Scanning Molecular Structure",
            processing: "Processing visual data through neural networks...",
            safetyIndex: "Safety Index",
            qualityDetected: "Quality Detected",
            clarity: "Clarity",
            color: "Color",
            sediment: "Sediment",
            recommendedActions: "Recommended Actions",
            awaitingSample: "Awaiting Sample",
            awaitingDesc: "Upload a photo on the left to begin the intelligent analysis process.",
            safetyAlert: "Safety Alert!",
            criticalContamination: "Critical contamination detected",
            alertAuthorities: "Alert Local Authorities",
            dismissWarning: "Dismiss Warning"
        },
        intel: {
            title: "Water Intelligence News",
            subtitle: "Latest from the Basin",
            trending: "Trending Updates",
            viewAllNews: "View All News",
            weeklyIntel: "Weekly Intelligence",
            weeklyDesc: "Get critical water quality alerts and basin reports directly in your inbox.",
            subscribe: "Subscribe Now",
            riskEngine: "Risk Assessment Engine",
            checkRisk: "Check Your Local Water Risk Score",
            riskDesc: "Enter your location to get a real-time risk assessment based on historical data, industrial reports, and community feedback.",
            locationPlaceholder: "Enter District or City (e.g., Mau, Azamgarh)",
            check: "Check",
            dataSources: "Data Sources",
            activeSensors: "Active Sensors",
            lastUpdate: "Last Update",
            realTimeSync: "Real-time Sync",
            assessmentResult: "Assessment Result",
            risk: "Risk",
            index: "Index",
            viewDetailedReport: "View Detailed Report",
            waitingInput: "Waiting for input",
            monitoringNetwork: "Monitoring Network",
            nearbyStations: "Nearby Stations",
            viewMap: "View Map",
            phLevel: "pH Level",
            turbidity: "Turbidity",
            tds: "TDS"
        }
    },
    hi: {
        nav: {
            home: 'होम',
            analyze: 'विश्लेषण',
            intel: 'इंटेलीजेंस',
            admin: 'प्रशासन मानचित्र',
            map: 'भारत का नक्शा',
            tools: 'उपकरण',
            faq: 'सामान्य प्रश्न',
            feedback: 'सुझाव',
            badges: 'बैज',
            signIn: 'साइन इन',
            signOut: 'साइन आउट',
            signedInAs: 'इस रूप में साइन इन हैं',
            sendFeedback: 'प्रतिक्रिया भेजें'
        },
        common: {
            loading: 'लोड हो रहा है...',
            error: 'त्रुटि',
            success: 'सफलता',
            yes: 'हाँ',
            no: 'नहीं',
            helpful: 'क्या यह मददगार था?',
            noResults: 'कोई परिणाम नहीं मिला',
            clearFilters: 'सभी फ़िल्टर साफ़ करें',
            contactSupport: 'सहायता से संपर्क करें',
            stillQuestions: 'अभी भी प्रश्न हैं?',
            supportDesc: 'हमारी टीम पानी से संबंधित किसी भी चिंता में आपकी मदद करने के लिए यहाँ है।',
            searchPlaceholder: 'प्रश्न खोजें...',
            knowledgeBase: 'ज्ञान केंद्र',
            questions: 'प्रश्न',
            faqDesc: 'पानी की गुणवत्ता, सुरक्षा और हमारे निगरानी उपकरणों का उपयोग करने के बारे में सामान्य प्रश्नों के उत्तर खोजें।',
            tryAdjust: 'अपनी खोज या श्रेणी फ़िल्टर को समायोजित करने का प्रयास करें।'
        },
        hero: {
            label: 'सरकारी पहल',
            titleStart: 'जल प्रशासन में हर नागरिक की',
            titleEnd: 'आवाज़ को सशक्त बनाना',
            desc: 'एक द्विभाषी वॉयस असिस्टेंट जो नागरिकों को जल प्रदूषण की रिपोर्ट करने, शिकायतों को ट्रैक करने और शासन सेवाओं तक तुरंत पहुंचने में मदद करता है।',
            btnPrimary: 'एआई विश्लेषण शुरू करें',
            btnSecondary: 'सहायता और अक्सर पूछे जाने वाले प्रश्न'
        },
        dashboard: {
            liveMonitor: 'लाइव बेसिन निगरानी',
            liveMonitorSub: 'वास्तविक समय सेंसर डेटा और सामुदायिक रिपोर्ट',
            systemOp: 'सिस्टम सक्रिय',
            aiAnalysis: 'स्थिति विश्लेषण',
            viewReport: 'पूरी रिपोर्ट देखें',
            chartTitle: 'जल गुणवत्ता रुझान',
            chartSub: '7-दिवसीय समग्र सूचकांक',
            keyParams: 'मुख्य पैरामीटर',
            recentReports: 'हालिया नागरिक रिपोर्ट',
            submitReport: 'रिपोर्ट भेजें',
            uploadPhoto: 'विश्लेषण के लिए फोटो अपलोड करें'
        },
        map: {
            title: 'जल गुणवत्ता मानचित्र',
            subtitle: 'क्षेत्रीय जल जोखिम और मुद्दे',
            all: 'सभी',
            critical: 'गंभीर',
            high: 'उच्च',
            medium: 'मध्यम',
            low: 'कम',
            keyIssues: 'मुख्य मुद्दे',
            getAdvice: 'सलाह लें'
        },
        analysis: {
            title: "दृश्य जल इंटेलिजेंस",
            subtitle: "अपने पानी के नमूने की एक फोटो अपलोड करें। हमारा उन्नत एआई तत्काल सुरक्षा स्कोर प्रदान करने के लिए स्पष्टता, रंग और तलछट के स्तर का विश्लेषण करेगा।",
            aiPowered: "एआई-संचालित डायग्नोस्टिक्स",
            howItWorks: "यह कैसे काम करता है",
            viewHistory: "इतिहास देखें",
            certified: "प्रमाणित विश्लेषण",
            accuracy: "92% सटीकता दर",
            uploadSample: "1. नमूना अपलोड करें",
            clickToUpload: "फोटो अपलोड करने के लिए क्लिक करें",
            dragDrop: "या यहाँ खींचें और छोड़ें",
            location: "स्थान (वैकल्पिक)",
            locationPlaceholder: "जैसे, मऊ ब्रिज, आजमगढ़",
            startAnalysis: "एआई विश्लेषण शुरू करें",
            analyzing: "विश्लेषण किया जा रहा है...",
            diagnosticResults: "2. नैदानिक परिणाम",
            scanning: "आणविक संरचना की स्कैनिंग",
            processing: "तंत्रिका नेटवर्क के माध्यम से दृश्य डेटा का प्रसंस्करण...",
            safetyIndex: "सुरक्षा सूचकांक",
            qualityDetected: "गुणवत्ता पाई गई",
            clarity: "स्पष्टता",
            color: "रंग",
            sediment: "तलछट",
            recommendedActions: "अनुशंसित कार्रवाइयां",
            awaitingSample: "नमूने की प्रतीक्षा है",
            awaitingDesc: "बुद्धिमान विश्लेषण प्रक्रिया शुरू करने के लिए बाईं ओर एक फोटो अपलोड करें।",
            safetyAlert: "सुरक्षा चेतावनी!",
            criticalContamination: "गंभीर संदूषण का पता चला",
            alertAuthorities: "स्थानीय अधिकारियों को सूचित करें",
            dismissWarning: "चेतावनी खारिज करें"
        },
        intel: {
            title: "जल इंटेलिजेंस समाचार",
            subtitle: "बेसिन से नवीनतम",
            trending: "ट्रेंडिंग अपडेट",
            viewAllNews: "सभी समाचार देखें",
            weeklyIntel: "साप्ताहिक इंटेलिजेंस",
            weeklyDesc: "सीधे अपने इनबॉक्स में महत्वपूर्ण जल गुणवत्ता अलर्ट और बेसिन रिपोर्ट प्राप्त करें।",
            subscribe: "अभी सदस्यता लें",
            riskEngine: "जोखिम मूल्यांकन इंजन",
            checkRisk: "अपने स्थानीय जल जोखिम स्कोर की जाँच करें",
            riskDesc: "ऐतिहासिक डेटा, औद्योगिक रिपोर्ट और सामुदायिक प्रतिक्रिया के आधार पर वास्तविक समय जोखिम मूल्यांकन प्राप्त करने के लिए अपना स्थान दर्ज करें।",
            locationPlaceholder: "जिला या शहर दर्ज करें (जैसे, मऊ, आजमगढ़)",
            check: "जांचें",
            dataSources: "डेटा स्रोत",
            activeSensors: "सक्रिय सेंसर",
            lastUpdate: "अंतिम अपडेट",
            realTimeSync: "वास्तविक समय सिंक",
            assessmentResult: "मूल्यांकन परिणाम",
            risk: "जोखिम",
            index: "सूचकांक",
            viewDetailedReport: "विस्तृत रिपोर्ट देखें",
            waitingInput: "इनपुट की प्रतीक्षा है",
            monitoringNetwork: "निगरानी नेटवर्क",
            nearbyStations: "आसपास के स्टेशन",
            viewMap: "मानचित्र देखें",
            phLevel: "पीएच स्तर",
            turbidity: "मैलापन",
            tds: "टीडीएस"
        }
    }
};