export interface MockReport {
  id: string;
  location: string;
  lat: number;
  lng: number;
  severity: number;
  status: "In Review" | "Escalated" | "Resolved" | "New";
  issue: string;
  reportedBy: string;
  avatar: string;
  avatarColor: string;
  time: string;
  timeAgo: string;
  images: number;
  aiAnalysis: { status: "Safe" | "Warning" | "Critical" | "Emergency"; confidence: number; algae: number };
  upvotes: number;
}

export const MOCK_REPORTS: MockReport[] = [
  {
    id: "JD-2026-00421",
    location: "City Center Ghat, Mau",
    lat: 25.9427,
    lng: 83.5539,
    severity: 85,
    status: "In Review",
    issue: "Dense algal bloom covering entire ghat surface",
    reportedBy: "Ramesh K.",
    avatar: "RK",
    avatarColor: "#EF4444",
    time: "11:52 PM",
    timeAgo: "2 hours ago",
    images: 3,
    aiAnalysis: { status: "Critical", confidence: 91, algae: 78 },
    upvotes: 24,
  },
  {
    id: "JD-2026-00419",
    location: "Textile Nala Junction, Mau",
    lat: 25.9398,
    lng: 83.5601,
    severity: 95,
    status: "Escalated",
    issue: "Black industrial discharge entering river from textile unit",
    reportedBy: "Sunita D.",
    avatar: "SD",
    avatarColor: "#7C3AED",
    time: "09:14 PM",
    timeAgo: "4 hours ago",
    images: 5,
    aiAnalysis: { status: "Emergency", confidence: 96, algae: 12 },
    upvotes: 47,
  },
  {
    id: "JD-2026-00415",
    location: "Sabzi Mandi Bridge, Mau",
    lat: 25.9445,
    lng: 83.5512,
    severity: 62,
    status: "Resolved",
    issue: "Foam and froth buildup near bridge pillar",
    reportedBy: "Arvind M.",
    avatar: "AM",
    avatarColor: "#F59E0B",
    time: "03:30 PM",
    timeAgo: "Yesterday",
    images: 2,
    aiAnalysis: { status: "Warning", confidence: 84, algae: 34 },
    upvotes: 18,
  },
  {
    id: "JD-2026-00408",
    location: "Harikeshpura Ghat, Mau",
    lat: 25.9461,
    lng: 83.5589,
    severity: 40,
    status: "Resolved",
    issue: "Garbage dumping and plastic waste on river bank",
    reportedBy: "Priya S.",
    avatar: "PS",
    avatarColor: "#10B981",
    time: "10:00 AM",
    timeAgo: "2 days ago",
    images: 4,
    aiAnalysis: { status: "Warning", confidence: 78, algae: 15 },
    upvotes: 31,
  },
  {
    id: "JD-2026-00401",
    location: "Raghunathpura Drain, Mau",
    lat: 25.9389,
    lng: 83.5567,
    severity: 90,
    status: "In Review",
    issue: "Untreated sewage discharge — strong odor, dark brown water",
    reportedBy: "Mohammad F.",
    avatar: "MF",
    avatarColor: "#EF4444",
    time: "06:45 PM",
    timeAgo: "3 days ago",
    images: 6,
    aiAnalysis: { status: "Critical", confidence: 89, algae: 55 },
    upvotes: 52,
  },
  {
    id: "JD-2026-00398",
    location: "Navpura Irrigation Canal, Mau",
    lat: 25.9312,
    lng: 83.5498,
    severity: 30,
    status: "Resolved",
    issue: "Water appears slightly turbid, farmers concerned",
    reportedBy: "Laxmi T.",
    avatar: "LT",
    avatarColor: "#06B6D4",
    time: "08:20 AM",
    timeAgo: "5 days ago",
    images: 1,
    aiAnalysis: { status: "Warning", confidence: 71, algae: 8 },
    upvotes: 9,
  },
  {
    id: "JD-2026-00391",
    location: "Belchaura Riverbank, Mau",
    lat: 25.9278,
    lng: 83.5445,
    severity: 20,
    status: "Resolved",
    issue: "Water level drop noticed — seasonal concern",
    reportedBy: "Geeta R.",
    avatar: "GR",
    avatarColor: "#22C55E",
    time: "04:10 PM",
    timeAgo: "1 week ago",
    images: 2,
    aiAnalysis: { status: "Safe", confidence: 88, algae: 5 },
    upvotes: 6,
  },
  {
    id: "JD-2026-00385",
    location: "Mau Junction Drain, Mau",
    lat: 25.9355,
    lng: 83.5623,
    severity: 75,
    status: "Escalated",
    issue: "Chemical smell from nearby factory — dead fish spotted",
    reportedBy: "Deepak V.",
    avatar: "DV",
    avatarColor: "#7C3AED",
    time: "01:30 PM",
    timeAgo: "1 week ago",
    images: 8,
    aiAnalysis: { status: "Emergency", confidence: 94, algae: 22 },
    upvotes: 63,
  },
];

export const MOCK_STATS = {
  totalReports: 421,
  todayReports: 8,
  resolvedThisWeek: 34,
  criticalActive: 3,
  avgResponseHours: 18,
  topReporter: "Mau City Center Area",
};
